### ISSUE TITLE
Really lost here.

### ISSUE THREAD

**Issue by Kadajett** [TwilioDevEd/video-quickstart-node#8]
I am attempting to implement the Twilio Video Node.js SDK, and there seems to be 100+ different tutorials, blog posts, etc, that all handle the token generation differently(and the Twilio SDK as a whole for that matter). 

I have seen these two methods, plus some more weird ones during my search. 

`token = new twilio.AccessToken(apiKeySid, accountSid, apiKeySecret);`

```
Twilio.tokens.create((err, response) => {
            if(err){
                console.error('Twilio Create Token Error: ', err);
                                // disregard the Boom error object. 
                return reply(Boom.badImplementation(err));
            }

        });
```

Is there a definitive way for me to create a user token, have the user attach to Twilio with that token?

**Comment by logicmason** [comment]
Agreed, it's really too bad Twilio doesn't have a general purpose REST API. Sending people to example apps made for their handful of example backends isn't ideal for those just looking for an API, especially when the apps obfuscate exactly what the payloads are by generating them through required sub-helper libraries.

**Comment by philnash** [comment]
Wow, sorry for the way late reply on this issue. I only just saw it resurface in my notifications.

@Kadajett the two token methods you see there are actually for different types of tokens (also confusing, I understand).

If you are generating an Access Token to be used by the Video SDK then you need to use the first example you posted, also seen in full in the code in this repo here: https://github.com/TwilioDevEd/video-quickstart-node/blob/master/index.js#L31-L43. This generates a JSON Web Token (JWT) that will authenticate the user with the Video SDK in JavaScript, iOS or Android.

The second example you post is used to create user credentials for the [Network Traversal Service](https://www.twilio.com/docs/api/stun-turn). These credentials can then be used as the `iceServers` property of a WebRTC RTCPeerConnection object when building your own WebRTC implementation.

@logicmason out API is as general purpose REST as we can make it. All the documentation for the resources, for example this [tokens resource we've mentioned here](https://www.twilio.com/docs/api/stun-turn), has examples using `curl` as well as the helper libraries and you can also see the output in JSON or XML. The helper libraries are not required and you can make requests to the Twilio API using any language that can speak HTTP. There is some confusion here as this example application generates a JWT without touching the API at all. You can see [the documentation and format of the JWT in the documentation here though](https://www.twilio.com/docs/api/rest/access-tokens).
